# Generated by Django 4.0.2 on 2022-02-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_types', '0001_initial'),
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_date', models.DateTimeField()),
                ('super_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_types.super_types')),
                ('super_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.super')),
            ],
        ),
    ]
